"""Assemble mandel.wasm — the escape-time kernel, as a WebAssembly module.

There is no toolchain here: no wat2wasm, no emscripten, and Apple's clang
cannot target wasm32. Rather than make the repository depend on one, the module
is emitted byte by byte from this file. Everything else in the project is
generated by committed Python with nothing installed, and this keeps that true;
the .wasm is committed alongside, so nobody needs to run this to use the page.

The module exports one function:

    render(out, lut, w, rows, x0, y0, step, maxIter, useBulb) -> iterations

It writes w*rows RGBA pixels at `out` and returns the total number of
iterations performed, which is what the page reports. Colour comes from a
1025-entry lookup table the caller writes at `lut`: 1024 entries around the
palette, and a final entry for the set itself. The table is what makes the two
kernels comparable — the JavaScript one reads the very same bytes, so any
difference in the picture is a difference in the arithmetic, not in the palette.

Usage:  python3 tools/build_wasm.py
"""

import pathlib
import struct

# --- the bits of the binary format we need ------------------------------

def uleb(n):
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        if n:
            out.append(b | 0x80)
        else:
            out.append(b)
            return bytes(out)


def sleb(n):
    out = bytearray()
    while True:
        b = n & 0x7F
        n >>= 7
        done = (n == 0 and not (b & 0x40)) or (n == -1 and (b & 0x40))
        out.append(b if done else b | 0x80)
        if done:
            return bytes(out)


def vec(items):
    return uleb(len(items)) + b''.join(items)


def section(sid, body):
    return bytes([sid]) + uleb(len(body)) + body


def name(s):
    b = s.encode()
    return uleb(len(b)) + b


I32, I64, F64 = 0x7F, 0x7E, 0x7C

# --- instructions -------------------------------------------------------

def op(code, *rest):
    return bytes([code]) + b''.join(rest)


get = lambda i: op(0x20, uleb(i))
setl = lambda i: op(0x21, uleb(i))
tee = lambda i: op(0x22, uleb(i))
i32c = lambda v: op(0x41, sleb(v))
i64c = lambda v: op(0x42, sleb(v))
f64c = lambda v: op(0x44, struct.pack('<d', v))

I32_ADD, I32_SUB, I32_MUL = op(0x6A), op(0x6B), op(0x6C)
I32_LT_S, I32_GE_S, I32_EQZ = op(0x48), op(0x4E), op(0x45)
I32_AND, I32_OR, I32_SHL, I32_SHR_U = op(0x71), op(0x72), op(0x74), op(0x76)
I64_AND, I64_OR, I64_SHR_U = op(0x83), op(0x84), op(0x88)
I32_WRAP_I64 = op(0xA7)
F64_ADD, F64_SUB, F64_MUL, F64_DIV = op(0xA0), op(0xA1), op(0xA2), op(0xA3)
F64_SQRT, F64_FLOOR, F64_NEG = op(0x9F), op(0x9C), op(0x9A)
F64_LE, F64_GE = op(0x65), op(0x66)
F64_REINT = op(0xBF)          # f64.reinterpret_i64
I64_REINT = op(0xBD)          # i64.reinterpret_f64
I32_TRUNC_F64_S = op(0xAA)
F64_CONVERT_I32_S = op(0xB7)
END, RETURN, DROP = op(0x0B), op(0x0F), op(0x1A)
BLOCK = lambda t=0x40: op(0x02, bytes([t]))
LOOP = lambda t=0x40: op(0x03, bytes([t]))
BR = lambda d: op(0x0C, uleb(d))
BR_IF = lambda d: op(0x0D, uleb(d))
CALL = lambda f: op(0x10, uleb(f))
I32_LOAD = lambda a=2, o=0: op(0x28, uleb(a), uleb(o))
I32_STORE = lambda a=2, o=0: op(0x36, uleb(a), uleb(o))


def body(locals_, code):
    """A function body: local declarations then instructions."""
    decls = vec([uleb(n) + bytes([t]) for n, t in locals_])
    inner = decls + code + END
    return uleb(len(inner)) + inner


# --- log2, which WebAssembly has no instruction for ---------------------
#
# Needed twice per escaped pixel for the smooth colouring. Done from the bits:
# the exponent field gives the integer part exactly, and the mantissa is put
# back as a number in [1,2) whose log is taken by the arctanh series, which
# converges fast enough over that range that four terms are far below what a
# 1024-entry palette can show.

LOG2E = 1.4426950408889634

def log2_body():
    X, E, M, S, S2 = 0, 1, 2, 3, 4       # local slots
    return body(
        [(1, I32), (3, F64)],
        # e = ((bits >> 52) & 0x7FF) - 1023
        get(X) + I64_REINT + i64c(52) + I64_SHR_U + i64c(0x7FF) + I64_AND
        + I32_WRAP_I64 + i32c(1023) + I32_SUB + setl(E)
        # m = mantissa with the exponent forced to 0, i.e. a value in [1,2)
        + get(X) + I64_REINT + i64c(0x000FFFFFFFFFFFFF) + I64_AND
        + i64c(0x3FF0000000000000) + I64_OR + F64_REINT + setl(M)
        # s = (m - 1) / (m + 1);  log(m) = 2*(s + s^3/3 + s^5/5 + s^7/7)
        + get(M) + f64c(1.0) + F64_SUB
        + get(M) + f64c(1.0) + F64_ADD + F64_DIV + setl(S)
        + get(S) + get(S) + F64_MUL + setl(S2)
        # Horner on s^2:  s * (2 + s2*(2/3 + s2*(2/5 + s2*2/7)))
        + get(S)
        + f64c(2.0 / 7.0) + get(S2) + F64_MUL + f64c(2.0 / 5.0) + F64_ADD
        + get(S2) + F64_MUL + f64c(2.0 / 3.0) + F64_ADD
        + get(S2) + F64_MUL + f64c(2.0) + F64_ADD
        + F64_MUL
        + f64c(LOG2E) + F64_MUL
        + get(E) + F64_CONVERT_I32_S + F64_ADD
    )


# --- the kernel ---------------------------------------------------------

BAILOUT = 256.0
PALETTE_STEPS = 1024


def build():
    OUT, LUT, W, ROWS, X0, Y0, STEP, MAXITER, BULB = range(9)
    (PY, PX, O, N, TOTAL, IDX,
     CI, CR, ZR, ZI, ZR2, ZI2, T, MU, QQ, XX) = range(9, 25)

    def store_lut_colour():
        """address, then the colour word, then store."""
        return (
            get(O)
            + get(MU) + F64_SQRT + f64c(0.19) + F64_MUL + setl(T)
            + get(T) + get(T) + F64_FLOOR + F64_SUB
            + f64c(float(PALETTE_STEPS)) + F64_MUL + I32_TRUNC_F64_S
            + i32c(PALETTE_STEPS - 1) + I32_AND + i32c(4) + I32_MUL
            + get(LUT) + I32_ADD + I32_LOAD()
            + I32_STORE()
        )

    def store_interior():
        return (get(O)
                + get(LUT) + i32c(PALETTE_STEPS * 4) + I32_ADD + I32_LOAD()
                + I32_STORE())

    # in the main cardioid?  q = (cr-1/4)^2 + ci^2 ;  q(q + cr - 1/4) <= ci^2/4
    cardioid = (
        get(CR) + f64c(0.25) + F64_SUB + setl(XX)
        + get(XX) + get(XX) + F64_MUL + get(CI) + get(CI) + F64_MUL + F64_ADD + setl(QQ)
        + get(QQ) + get(QQ) + get(XX) + F64_ADD + F64_MUL
        + f64c(0.25) + get(CI) + F64_MUL + get(CI) + F64_MUL + F64_LE
    )
    # or in the period-2 bulb: (cr+1)^2 + ci^2 <= 1/16
    bulb2 = (
        get(CR) + f64c(1.0) + F64_ADD + setl(XX)
        + get(XX) + get(XX) + F64_MUL + get(CI) + get(CI) + F64_MUL + F64_ADD
        + f64c(0.0625) + F64_LE
    )

    px_loop = (
        # cr = x0 + px*step ; o = out + (py*w + px)*4
        get(X0) + get(PX) + F64_CONVERT_I32_S + get(STEP) + F64_MUL + F64_ADD + setl(CR)
        + get(OUT) + get(PY) + get(W) + I32_MUL + get(PX) + I32_ADD
        + i32c(4) + I32_MUL + I32_ADD + setl(O)

        + BLOCK()                                  # one pixel
        # interior shortcut
        + BLOCK()
        + get(BULB) + I32_EQZ + BR_IF(0)
        + cardioid + bulb2 + I32_OR + I32_EQZ + BR_IF(0)
        + get(TOTAL) + i32c(1) + I32_ADD + setl(TOTAL)
        + store_interior()
        + BR(1)
        + END

        # the escape loop
        + f64c(0.0) + setl(ZR) + f64c(0.0) + setl(ZI)
        + f64c(0.0) + setl(ZR2) + f64c(0.0) + setl(ZI2)
        + i32c(0) + setl(N)
        + BLOCK() + LOOP()
        + get(N) + get(MAXITER) + I32_GE_S + BR_IF(1)
        + get(ZR2) + get(ZI2) + F64_ADD + f64c(BAILOUT) + F64_GE + BR_IF(1)
        + f64c(2.0) + get(ZR) + F64_MUL + get(ZI) + F64_MUL + get(CI) + F64_ADD + setl(ZI)
        + get(ZR2) + get(ZI2) + F64_SUB + get(CR) + F64_ADD + setl(ZR)
        + get(ZR) + get(ZR) + F64_MUL + setl(ZR2)
        + get(ZI) + get(ZI) + F64_MUL + setl(ZI2)
        + get(N) + i32c(1) + I32_ADD + setl(N)
        + BR(0) + END + END
        + get(TOTAL) + get(N) + I32_ADD + setl(TOTAL)

        + BLOCK()
        + get(N) + get(MAXITER) + I32_LT_S + BR_IF(0)
        + store_interior()
        + BR(1)
        + END
        # mu = n + 1 - log2( log2(|z|^2) / 2 )
        + get(N) + F64_CONVERT_I32_S + f64c(1.0) + F64_ADD
        + get(ZR2) + get(ZI2) + F64_ADD + CALL(0) + f64c(0.5) + F64_MUL + CALL(0)
        + F64_SUB + setl(MU)
        + store_lut_colour()
        + END
    )

    code = (
        i32c(0) + setl(TOTAL)
        + i32c(0) + setl(PY)
        + BLOCK() + LOOP()
        + get(PY) + get(ROWS) + I32_GE_S + BR_IF(1)
        + get(Y0) + get(PY) + F64_CONVERT_I32_S + get(STEP) + F64_MUL + F64_ADD + setl(CI)
        + i32c(0) + setl(PX)
        + BLOCK() + LOOP()
        + get(PX) + get(W) + I32_GE_S + BR_IF(1)
        + px_loop
        + get(PX) + i32c(1) + I32_ADD + setl(PX)
        + BR(0) + END + END
        + get(PY) + i32c(1) + I32_ADD + setl(PY)
        + BR(0) + END + END
        + get(TOTAL)
    )

    # After the nine parameters: six i32 locals (py, px, o, n, total, idx)
    # then ten f64 (ci, cr, zr, zi, zr2, zi2, t, mu, qq, xx).
    render = body([(6, I32), (10, F64)], code)

    types = vec([
        bytes([0x60]) + vec([bytes([F64])]) + vec([bytes([F64])]),
        bytes([0x60]) + vec([bytes([t]) for t in
                             (I32, I32, I32, I32, F64, F64, F64, I32, I32)])
        + vec([bytes([I32])]),
    ])
    imports = vec([name('env') + name('mem') + bytes([0x02, 0x00]) + uleb(1)])
    funcs = vec([uleb(0), uleb(1)])
    exports = vec([name('render') + bytes([0x00]) + uleb(1)])
    codes = vec([log2_body(), render])

    return (b'\0asm' + struct.pack('<I', 1)
            + section(1, types) + section(2, imports) + section(3, funcs)
            + section(7, exports) + section(10, codes))


if __name__ == '__main__':
    out = pathlib.Path(__file__).resolve().parent.parent / 'mandel.wasm'
    data = build()
    out.write_bytes(data)
    print(f'{out.name}: {len(data)} bytes')
